// Code generated by ent, DO NOT EDIT.

package challengegroup

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the challengegroup type in the database.
	Label = "challenge_group"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// EdgeChallenges holds the string denoting the challenges edge name in mutations.
	EdgeChallenges = "challenges"
	// EdgeCategory holds the string denoting the category edge name in mutations.
	EdgeCategory = "category"
	// EdgeEpisodeRound holds the string denoting the episode_round edge name in mutations.
	EdgeEpisodeRound = "episode_round"
	// Table holds the table name of the challengegroup in the database.
	Table = "challenge_groups"
	// ChallengesTable is the table that holds the challenges relation/edge. The primary key declared below.
	ChallengesTable = "challenge_group_challenges"
	// ChallengesInverseTable is the table name for the Challenge entity.
	// It exists in this package in order to avoid circular dependency with the "challenge" package.
	ChallengesInverseTable = "challenges"
	// CategoryTable is the table that holds the category relation/edge. The primary key declared below.
	CategoryTable = "category_challenge_groups"
	// CategoryInverseTable is the table name for the Category entity.
	// It exists in this package in order to avoid circular dependency with the "category" package.
	CategoryInverseTable = "categories"
	// EpisodeRoundTable is the table that holds the episode_round relation/edge. The primary key declared below.
	EpisodeRoundTable = "episode_round_categories"
	// EpisodeRoundInverseTable is the table name for the EpisodeRound entity.
	// It exists in this package in order to avoid circular dependency with the "episoderound" package.
	EpisodeRoundInverseTable = "episode_rounds"
)

// Columns holds all SQL columns for challengegroup fields.
var Columns = []string{
	FieldID,
}

var (
	// ChallengesPrimaryKey and ChallengesColumn2 are the table columns denoting the
	// primary key for the challenges relation (M2M).
	ChallengesPrimaryKey = []string{"challenge_group_id", "challenge_id"}
	// CategoryPrimaryKey and CategoryColumn2 are the table columns denoting the
	// primary key for the category relation (M2M).
	CategoryPrimaryKey = []string{"category_id", "challenge_group_id"}
	// EpisodeRoundPrimaryKey and EpisodeRoundColumn2 are the table columns denoting the
	// primary key for the episode_round relation (M2M).
	EpisodeRoundPrimaryKey = []string{"episode_round_id", "challenge_group_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the ChallengeGroup queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByChallengesCount orders the results by challenges count.
func ByChallengesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newChallengesStep(), opts...)
	}
}

// ByChallenges orders the results by challenges terms.
func ByChallenges(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChallengesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCategoryCount orders the results by category count.
func ByCategoryCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCategoryStep(), opts...)
	}
}

// ByCategory orders the results by category terms.
func ByCategory(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCategoryStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByEpisodeRoundCount orders the results by episode_round count.
func ByEpisodeRoundCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEpisodeRoundStep(), opts...)
	}
}

// ByEpisodeRound orders the results by episode_round terms.
func ByEpisodeRound(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEpisodeRoundStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newChallengesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChallengesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, ChallengesTable, ChallengesPrimaryKey...),
	)
}
func newCategoryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CategoryInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, CategoryTable, CategoryPrimaryKey...),
	)
}
func newEpisodeRoundStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EpisodeRoundInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, EpisodeRoundTable, EpisodeRoundPrimaryKey...),
	)
}
