// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kevindamm/q-party/ent/challengegroup"
	"github.com/kevindamm/q-party/ent/predicate"
)

// ChallengeGroupDelete is the builder for deleting a ChallengeGroup entity.
type ChallengeGroupDelete struct {
	config
	hooks    []Hook
	mutation *ChallengeGroupMutation
}

// Where appends a list predicates to the ChallengeGroupDelete builder.
func (cgd *ChallengeGroupDelete) Where(ps ...predicate.ChallengeGroup) *ChallengeGroupDelete {
	cgd.mutation.Where(ps...)
	return cgd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cgd *ChallengeGroupDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, cgd.sqlExec, cgd.mutation, cgd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (cgd *ChallengeGroupDelete) ExecX(ctx context.Context) int {
	n, err := cgd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cgd *ChallengeGroupDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(challengegroup.Table, sqlgraph.NewFieldSpec(challengegroup.FieldID, field.TypeInt))
	if ps := cgd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, cgd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	cgd.mutation.done = true
	return affected, err
}

// ChallengeGroupDeleteOne is the builder for deleting a single ChallengeGroup entity.
type ChallengeGroupDeleteOne struct {
	cgd *ChallengeGroupDelete
}

// Where appends a list predicates to the ChallengeGroupDelete builder.
func (cgdo *ChallengeGroupDeleteOne) Where(ps ...predicate.ChallengeGroup) *ChallengeGroupDeleteOne {
	cgdo.cgd.mutation.Where(ps...)
	return cgdo
}

// Exec executes the deletion query.
func (cgdo *ChallengeGroupDeleteOne) Exec(ctx context.Context) error {
	n, err := cgdo.cgd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{challengegroup.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cgdo *ChallengeGroupDeleteOne) ExecX(ctx context.Context) {
	if err := cgdo.Exec(ctx); err != nil {
		panic(err)
	}
}
