// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kevindamm/q-party/ent/episoderound"
	"github.com/kevindamm/q-party/ent/predicate"
)

// EpisodeRoundDelete is the builder for deleting a EpisodeRound entity.
type EpisodeRoundDelete struct {
	config
	hooks    []Hook
	mutation *EpisodeRoundMutation
}

// Where appends a list predicates to the EpisodeRoundDelete builder.
func (erd *EpisodeRoundDelete) Where(ps ...predicate.EpisodeRound) *EpisodeRoundDelete {
	erd.mutation.Where(ps...)
	return erd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (erd *EpisodeRoundDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, erd.sqlExec, erd.mutation, erd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (erd *EpisodeRoundDelete) ExecX(ctx context.Context) int {
	n, err := erd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (erd *EpisodeRoundDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(episoderound.Table, sqlgraph.NewFieldSpec(episoderound.FieldID, field.TypeInt))
	if ps := erd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, erd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	erd.mutation.done = true
	return affected, err
}

// EpisodeRoundDeleteOne is the builder for deleting a single EpisodeRound entity.
type EpisodeRoundDeleteOne struct {
	erd *EpisodeRoundDelete
}

// Where appends a list predicates to the EpisodeRoundDelete builder.
func (erdo *EpisodeRoundDeleteOne) Where(ps ...predicate.EpisodeRound) *EpisodeRoundDeleteOne {
	erdo.erd.mutation.Where(ps...)
	return erdo
}

// Exec executes the deletion query.
func (erdo *EpisodeRoundDeleteOne) Exec(ctx context.Context) error {
	n, err := erdo.erd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{episoderound.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (erdo *EpisodeRoundDeleteOne) ExecX(ctx context.Context) {
	if err := erdo.Exec(ctx); err != nil {
		panic(err)
	}
}
