name = "q-party-website"
main = "src/router.ts"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "../public"

[observability]
enabled = true

[ai]
binding = "WHISPER"

[[d1_databases]]
binding = "DB"
database_name = "q-party-db"
database_id = "b806fe22-c685-40b2-98ea-808c4bba193f"

# for media (images, videos, audio) clues
[[r2_buckets]]
binding = "MEDIA"
bucket_name = "triviamedia"

# DurableObject bindings
[durable_objects]
bindings = [
  {name = "LOBBIES", class_name = "LobbyServer" },
  {name = "GAMEPLAY", class_name = "GameplayServer" }
]

# DurableObject classnames
[[migrations]]
tag = "v1"
new_classes = ["LobbyServer", "ContestantServer"]

[vars]
BASE_URL = "https://q-party.kevindamm.com"

[vars.dev]
BASE_URL = "https://localhost"
