// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Challenge is the predicate function for challenge builders.
type Challenge func(*sql.Selector)

// ChallengeGroup is the predicate function for challengegroup builders.
type ChallengeGroup func(*sql.Selector)

// Episode is the predicate function for episode builders.
type Episode func(*sql.Selector)

// EpisodeRound is the predicate function for episoderound builders.
type EpisodeRound func(*sql.Selector)
